2019-04-04 22:55:42,250 - pyftpdlib - INFO - >>> starting FTP server on 192.168.31.232:21, pid=10268 <<<
2019-04-04 22:55:42,251 - pyftpdlib - INFO - concurrency model: async
2019-04-04 22:55:42,251 - pyftpdlib - INFO - masquerade (NAT) address: None
2019-04-04 22:55:42,252 - pyftpdlib - INFO - passive ports: None
2019-04-04 22:56:08,808 - pyftpdlib - INFO - 192.168.31.232:50111-[] FTP session opened (connect)
2019-04-04 22:56:08,819 - pyftpdlib - INFO - 192.168.31.232:50111-[user] USER 'user' logged in.
2019-04-04 22:56:08,841 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\Matlab_test_one.doc 550 'Not a directory.'
2019-04-04 22:56:08,844 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\Share_Files 250
2019-04-04 22:56:08,846 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\Share_Files 250
2019-04-04 22:56:08,847 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\Share_Files 250
2019-04-04 22:56:08,860 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (1).txt 550 'No such file or directory.'
2019-04-04 22:56:08,862 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (10).txt 550 'No such file or directory.'
2019-04-04 22:56:08,863 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (2).txt 550 'No such file or directory.'
2019-04-04 22:56:08,864 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (3).txt 550 'No such file or directory.'
2019-04-04 22:56:08,865 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (4).txt 550 'No such file or directory.'
2019-04-04 22:56:08,866 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (5).txt 550 'No such file or directory.'
2019-04-04 22:56:08,868 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (6).txt 550 'No such file or directory.'
2019-04-04 22:56:08,869 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (7).txt 550 'No such file or directory.'
2019-04-04 22:56:08,869 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (8).txt 550 'No such file or directory.'
2019-04-04 22:56:08,870 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\a (9).txt 550 'No such file or directory.'
2019-04-04 22:56:08,890 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\fuction1.m 550 'Not a directory.'
2019-04-04 22:56:08,891 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\fuction2.m 550 'Not a directory.'
2019-04-04 22:56:08,892 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\practice_one_function.m 550 'Not a directory.'
2019-04-04 22:56:08,893 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\practice_one_max.m 550 'Not a directory.'
2019-04-04 22:56:08,894 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\practice_one_one.m 550 'Not a directory.'
2019-04-04 22:56:08,895 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\practice_one_otherfunction.m 550 'Not a directory.'
2019-04-04 22:56:08,896 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\practice_one_two.m 550 'Not a directory.'
2019-04-04 22:56:08,897 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\test1.m 550 'Not a directory.'
2019-04-04 22:56:08,898 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\test2.m 550 'Not a directory.'
2019-04-04 22:56:08,900 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录\test3.m 550 'Not a directory.'
2019-04-04 22:56:49,039 - pyftpdlib - INFO - 192.168.31.232:50111-[user] RETR D:\Desktop\Matalab工程目录\Share_Files\a (2).txt completed=1 bytes=1818 seconds=0.344
2019-04-04 22:58:35,303 - pyftpdlib - INFO - 192.168.31.232:50111-[user] CWD D:\Desktop\Matalab工程目录 250
2019-04-04 22:58:35,313 - pyftpdlib - INFO - 192.168.31.232:50111-[user] STOR D:\Desktop\Matalab工程目录\-Share_Files-a (2).txt completed=1 bytes=1818 seconds=0.0
2019-04-04 22:59:42,215 - pyftpdlib - INFO - received interrupt signal
2019-04-04 22:59:42,216 - pyftpdlib - INFO - >>> shutting down FTP server (2 active socket fds) <<<
2019-04-04 22:59:42,217 - pyftpdlib - INFO - 192.168.31.232:50111-[user] FTP session closed (disconnect).
